<?php

namespace ContainerLGM5fFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y5jTp7QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y5jTp7Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y5jTp7Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AutocompleteController::autocompleteAction' => ['privates', '.service_locator.YmyVJmt', 'get_ServiceLocator_YmyVJmtService', true],
            'App\\Controller\\CategoryController::create' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.yG1ekMK', 'get_ServiceLocator_YG1ekMKService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController::update' => ['privates', '.service_locator.yG1ekMK', 'get_ServiceLocator_YG1ekMKService', true],
            'App\\Controller\\MovieController::create' => ['privates', '.service_locator.XbNHOHY', 'get_ServiceLocator_XbNHOHYService', true],
            'App\\Controller\\MovieController::delete' => ['privates', '.service_locator.wyBe1f9', 'get_ServiceLocator_WyBe1f9Service', true],
            'App\\Controller\\MovieController::details' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\MovieController::index' => ['privates', '.service_locator.ZGZ2GBs', 'get_ServiceLocator_ZGZ2GBsService', true],
            'App\\Controller\\ProjectController::details' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\ProjectController::home' => ['privates', '.service_locator.l2Mm6xO', 'get_ServiceLocator_L2Mm6xOService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AutocompleteController:autocompleteAction' => ['privates', '.service_locator.YmyVJmt', 'get_ServiceLocator_YmyVJmtService', true],
            'App\\Controller\\CategoryController:create' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.yG1ekMK', 'get_ServiceLocator_YG1ekMKService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController:update' => ['privates', '.service_locator.yG1ekMK', 'get_ServiceLocator_YG1ekMKService', true],
            'App\\Controller\\MovieController:create' => ['privates', '.service_locator.XbNHOHY', 'get_ServiceLocator_XbNHOHYService', true],
            'App\\Controller\\MovieController:delete' => ['privates', '.service_locator.wyBe1f9', 'get_ServiceLocator_WyBe1f9Service', true],
            'App\\Controller\\MovieController:details' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\MovieController:index' => ['privates', '.service_locator.ZGZ2GBs', 'get_ServiceLocator_ZGZ2GBsService', true],
            'App\\Controller\\ProjectController:details' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\ProjectController:home' => ['privates', '.service_locator.l2Mm6xO', 'get_ServiceLocator_L2Mm6xOService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AutocompleteController::autocompleteAction' => '?',
            'App\\Controller\\CategoryController::create' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::update' => '?',
            'App\\Controller\\MovieController::create' => '?',
            'App\\Controller\\MovieController::delete' => '?',
            'App\\Controller\\MovieController::details' => '?',
            'App\\Controller\\MovieController::index' => '?',
            'App\\Controller\\ProjectController::details' => '?',
            'App\\Controller\\ProjectController::home' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AutocompleteController:autocompleteAction' => '?',
            'App\\Controller\\CategoryController:create' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:update' => '?',
            'App\\Controller\\MovieController:create' => '?',
            'App\\Controller\\MovieController:delete' => '?',
            'App\\Controller\\MovieController:details' => '?',
            'App\\Controller\\MovieController:index' => '?',
            'App\\Controller\\ProjectController:details' => '?',
            'App\\Controller\\ProjectController:home' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
