<?php

namespace ContainerLGM5fFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZGZ2GBsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZGZ2GBs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZGZ2GBs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movieRepository' => ['privates', 'App\\Repository\\MoovieRepository', 'getMoovieRepositoryService', true],
        ], [
            'movieRepository' => 'App\\Repository\\MoovieRepository',
        ]);
    }
}
